name: testing
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # --- PERBAIKAN DI SINI ---
  # Paket ini digeser ke kiri agar SEJAJAR dengan tulisan 'flutter:'
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8 

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_launcher.png" 
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # Aset Gambar
  assets:
    - assets/images/
    - assets/region_2/